name: ci-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: yinnohs
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: setup Go 1.23.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23.0
        id: go
      
      - name: check code into the go module directory
        uses: actions/checkout@v2

      - name: setup postgres with migrations
        run: make migrateup

      - name: Test
        run: make test