name: ci-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: setup Go 1.23.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23.0
        id: go
      
      - name: check code into the go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test